INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Chloe von Einzbern", "view/assets/img/servant/Chloe.png", "view/assets/img/servant/thumb/Chloe.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mysterious Alter Ego Lambda", "view/assets/img/servant/Lambda.png", "view/assets/img/servant/thumb/Lambda.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Astolfo", "view/assets/img/servant/Astolfo.png", "view/assets/img/servant/thumb/Astolfo.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Sakatsuki Miyu", "view/assets/img/servant/Miyu.png", "view/assets/img/servant/thumb/Miyu.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Osakabehime", "view/assets/img/servant/Osakabehime.png", "view/assets/img/servant/thumb/Osakabehime.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("BB (Summer)", "view/assets/img/servant/BB_Summer.png", "view/assets/img/servant/thumb/BB_Summer.png", 100, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Illyasviel von Einzbern", "view/assets/img/servant/Illya.png", "view/assets/img/servant/thumb/Illya.png", 96, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Xuanzang Sanzang", "view/assets/img/servant/Sanzang.png", "view/assets/img/servant/thumb/Sanzang.png", 96, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ibuki Douji", "view/assets/img/servant/Ibuki.png", "view/assets/img/servant/thumb/Ibuki.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Astolfo (Christmas)", "view/assets/img/servant/Astolfo_Christmas.png", "view/assets/img/servant/thumb/Astolfo_Christmas.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mordred", "view/assets/img/servant/Mordred.png", "view/assets/img/servant/thumb/Mordred.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Altera", "view/assets/img/servant/Altera.png", "view/assets/img/servant/thumb/Altera.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Super Orion", "view/assets/img/servant/Super_Orion.png", "view/assets/img/servant/thumb/Super_Orion.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Bradamante", "view/assets/img/servant/Bradamante.png", "view/assets/img/servant/thumb/Bradamante.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Tamamo no Mae (Summer)", "view/assets/img/servant/Tamamo_Summer.png", "view/assets/img/servant/thumb/Tamamo_Summer.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Achilles", "view/assets/img/servant/Achilles.png", "view/assets/img/servant/thumb/Achilles.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nero Claudius (Summer)", "view/assets/img/servant/Nero_Summer.png", "view/assets/img/servant/thumb/Nero_Summer.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mysterious Heroine X", "view/assets/img/servant/X.png", "view/assets/img/servant/thumb/X.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Jack the Ripper", "view/assets/img/servant/Jack.png", "view/assets/img/servant/thumb/Jack.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Jeanne d"Arc Alter", "view/assets/img/servant/Jalter.png", "view/assets/img/servant/thumb/Jalter.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ganesha", "view/assets/img/servant/Ganesha.png", "view/assets/img/servant/thumb/Ganesha.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Van Gogh", "view/assets/img/servant/Van_Gogh.png", "view/assets/img/servant/thumb/Van_Gogh.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Abigail Williams", "view/assets/img/servant/Abby.png", "view/assets/img/servant/thumb/Abby.png", 90, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Paul Bunyan", "view/assets/img/servant/Bunyan.png", "view/assets/img/servant/thumb/Bunyan.png", 85, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Karna (Santa)", "view/assets/img/servant/Karna_Santa.png", "view/assets/img/servant/thumb/Karna_Santa.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Tomoe Gozen (Summer)", "view/assets/img/servant/Tomoe_Summer.png", "view/assets/img/servant/thumb/Tomoe_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Katsushika Hokusai (Summer)", "view/assets/img/servant/Hokusai_Summer.png", "view/assets/img/servant/thumb/Hokusai_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Lan Ling Wang", "view/assets/img/servant/Lan_Ling.png", "view/assets/img/servant/thumb/Lan_Ling.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Queen Medb (Summer)", "view/assets/img/servant/Medb_Summer.png", "view/assets/img/servant/thumb/Medb_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Suzuka Gozen", "view/assets/img/servant/Suzuka.png", "view/assets/img/servant/thumb/Suzuka.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Siegfried", "view/assets/img/servant/Siegfried.png", "view/assets/img/servant/thumb/Siegfried.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nero Claudius", "view/assets/img/servant/Nero.png", "view/assets/img/servant/thumb/Nero.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Artoria Lily", "view/assets/img/servant/Altria_Lily.png", "view/assets/img/servant/thumb/Altria_Lily.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Artoria Alter", "view/assets/img/servant/Altria_Alter.png", "view/assets/img/servant/thumb/Altria_Alter.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Florence Nightingale (Santa)", "view/assets/img/servant/Nightingale_Santa.png", "view/assets/img/servant/thumb/Nightingale_Santa.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Calamity Jane", "view/assets/img/servant/Jane.png", "view/assets/img/servant/thumb/Jane.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Altera (Santa)", "view/assets/img/servant/Altera_Santa.png", "view/assets/img/servant/thumb/Altera_Santa.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Tomoe Gozen", "view/assets/img/servant/Tomoe.png", "view/assets/img/servant/thumb/Tomoe.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Yu Mei-ren (Summer)", "view/assets/img/servant/Yu_Summer.png", "view/assets/img/servant/thumb/Yu_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Utsumi Erice", "view/assets/img/servant/Erice.png", "view/assets/img/servant/thumb/Erice.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nagao Kagetora", "view/assets/img/servant/Kagetora.png", "view/assets/img/servant/thumb/Kagetora.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Valkyrie", "view/assets/img/servant/Valkyrie.png", "view/assets/img/servant/thumb/Valkyrie.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Medusa Lily", "view/assets/img/servant/Medusa_Lily.png", "view/assets/img/servant/thumb/Medusa_Lily.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Jeanne d"Arc Alter Lily", "view/assets/img/servant/Jailter.png", "view/assets/img/servant/thumb/Jailter.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Gareth", "view/assets/img/servant/Gareth.png", "view/assets/img/servant/thumb/Gareth.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mary Read", "view/assets/img/servant/Mary.png", "view/assets/img/servant/thumb/Mary.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Marie Antoinette", "view/assets/img/servant/Marie.png", "view/assets/img/servant/thumb/Marie.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Tamamo no Mae", "view/assets/img/servant/Tamamo.png", "view/assets/img/servant/thumb/Tamamo.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Shuten Douji (Caster)", "view/assets/img/servant/Shuten_Caster.png", "view/assets/img/servant/thumb/Shuten_Caster.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Sieg", "view/assets/img/servant/Sieg.png", "view/assets/img/servant/thumb/Sieg.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Queen of Sheba", "view/assets/img/servant/Sheba.png", "view/assets/img/servant/thumb/Sheba.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("King Gilgamesh", "view/assets/img/servant/King_Gil.png", "view/assets/img/servant/thumb/King_Gil.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Irisviel von Einzbern", "view/assets/img/servant/Irisviel.png", "view/assets/img/servant/thumb/Irisviel.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Kiichi Hogen", "view/assets/img/servant/Hogen.png", "view/assets/img/servant/thumb/Hogen.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Okita Souji (Summer)", "view/assets/img/servant/Okita_Summer.png", "view/assets/img/servant/thumb/Okita_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Gray", "view/assets/img/servant/Gray.png", "view/assets/img/servant/thumb/Gray.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ushiwakamaru (Summer)", "view/assets/img/servant/Ushiwaka_Summer.png", "view/assets/img/servant/thumb/Ushiwaka_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mochizuki Chiyome", "view/assets/img/servant/Chiyome.png", "view/assets/img/servant/thumb/Chiyome.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nitocris (Summer)", "view/assets/img/servant/Nitocris_Summer.png", "view/assets/img/servant/thumb/Nitocris_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Wu Zetian", "view/assets/img/servant/Wu.png", "view/assets/img/servant/thumb/Wu.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Stheno", "view/assets/img/servant/Stheno.png", "view/assets/img/servant/thumb/Stheno.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Minamoto no Raikou", "view/assets/img/servant/Raikou.png", "view/assets/img/servant/thumb/Raikou.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Jeanne d"Arc Alter (Summer)", "view/assets/img/servant/Jalter_Summer.png", "view/assets/img/servant/thumb/Jalter_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Atalante Alter", "view/assets/img/servant/Atalante_Alter.png", "view/assets/img/servant/thumb/Atalante_Alter.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Oda Nobunaga (Summer)", "view/assets/img/servant/Nobbu_Summer.png", "view/assets/img/servant/thumb/Nobbu_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Penthesilea", "view/assets/img/servant/Penthesilea.png", "view/assets/img/servant/thumb/Penthesilea.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Martha (Summer)", "view/assets/img/servant/Martha_Summer.png", "view/assets/img/servant/thumb/Martha_Summer.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mecha Eli", "view/assets/img/servant/Mecha_Eli.png", "view/assets/img/servant/thumb/Mecha_Eli.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Passionlip", "view/assets/img/servant/Lip.png", "view/assets/img/servant/thumb/Lip.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mysterious Heroine XX", "view/assets/img/servant/XX.png", "view/assets/img/servant/thumb/XX.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mash Kyrielight", "view/assets/img/servant/Mash.png", "view/assets/img/servant/thumb/Mash.png", 80, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("BB", "view/assets/img/servant/BB.png", "view/assets/img/servant/thumb/BB.png", 79, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nursery Rhyme", "view/assets/img/servant/Nursery.png", "view/assets/img/servant/thumb/Nursery.png", 73, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Helena Blavatsky", "view/assets/img/servant/Helena.png", "view/assets/img/servant/thumb/Helena.png", 72, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Elizabeth Bathory (Brave)", "view/assets/img/servant/Eli_Brave.png", "view/assets/img/servant/thumb/Eli_Brave.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Chevalier d"Eon", "view/assets/img/servant/Deon.png", "view/assets/img/servant/thumb/Deon.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Anne Bonny", "view/assets/img/servant/Anne.png", "view/assets/img/servant/thumb/Anne.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Oda Nobunaga", "view/assets/img/servant/Nobbu.png", "view/assets/img/servant/thumb/Nobbu.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Arash", "view/assets/img/servant/Arash.png", "view/assets/img/servant/thumb/Arash.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Kiyohime (Summer)", "view/assets/img/servant/Kiyohime_Summer.png", "view/assets/img/servant/thumb/Kiyohime_Summer.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Elizabeth Bathory", "view/assets/img/servant/Eli.png", "view/assets/img/servant/thumb/Eli.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ishtar (Summer)", "view/assets/img/servant/Ishtar_Summer.png", "view/assets/img/servant/thumb/Ishtar_Summer.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mandricardo", "view/assets/img/servant/Mandricardo.png", "view/assets/img/servant/thumb/Mandricardo.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Nitocris", "view/assets/img/servant/Nitocris.png", "view/assets/img/servant/thumb/Nitocris.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Hans Christian Andersen", "view/assets/img/servant/Andersen.png", "view/assets/img/servant/thumb/Andersen.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Scathach (Summer)", "view/assets/img/servant/Scathach_Summer.png", "view/assets/img/servant/thumb/Scathach_Summer.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Chacha", "view/assets/img/servant/Chacha.png", "view/assets/img/servant/thumb/Chacha.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ibaraki Douji", "view/assets/img/servant/Ibaraki.png", "view/assets/img/servant/thumb/Ibaraki.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Frankenstein", "view/assets/img/servant/Fran.png", "view/assets/img/servant/thumb/Fran.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Tamamo Cat", "view/assets/img/servant/Tamamo_Cat.png", "view/assets/img/servant/thumb/Tamamo_Cat.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Gorgon", "view/assets/img/servant/Gorgon.png", "view/assets/img/servant/thumb/Gorgon.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Antonio Salieri", "view/assets/img/servant/Salieri.png", "view/assets/img/servant/thumb/Salieri.png", 70, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Paris", "view/assets/img/servant/Paris.png", "view/assets/img/servant/thumb/Paris.png", 65, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Salome", "view/assets/img/servant/Salome.png", "view/assets/img/servant/thumb/Salome.png", 65, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Kid Gil", "view/assets/img/servant/Kid_Gil.png", "view/assets/img/servant/thumb/Kid_Gil.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Euryale", "view/assets/img/servant/Euryale.png", "view/assets/img/servant/thumb/Euryale.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Oda Nobukatsu", "view/assets/img/servant/Nobukatsu.png", "view/assets/img/servant/thumb/Nobukatsu.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Ushiwakamaru", "view/assets/img/servant/Ushiwaka.png", "view/assets/img/servant/thumb/Ushiwaka.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Boudica", "view/assets/img/servant/Boudica.png", "view/assets/img/servant/thumb/Boudica.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Medusa", "view/assets/img/servant/Medusa.png", "view/assets/img/servant/thumb/Medusa.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Hassan of the Serenity", "view/assets/img/servant/Serenity.png", "view/assets/img/servant/thumb/Serenity.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Charlotte Corday", "view/assets/img/servant/Charlotte.png", "view/assets/img/servant/thumb/Charlotte.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Mata Hari", "view/assets/img/servant/Mata_Hari.png", "view/assets/img/servant/thumb/Mata_Hari.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, level, is_has) VALUES ("Kiyohime", "view/assets/img/servant/Kiyohime.png", "view/assets/img/servant/thumb/Kiyohime.png", 60, true);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Manannan mac Lir", "view/assets/img/servant/Bazett.png", "view/assets/img/servant/thumb/Bazett.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Hai Ba Trung", "view/assets/img/servant/Trung_Sisters.png", "view/assets/img/servant/thumb/Trung_Sisters.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Kukulkan", "view/assets/img/servant/Kukulkan.png", "view/assets/img/servant/thumb/Kukulkan.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Jacques de Molay", "view/assets/img/servant/Molay.png", "view/assets/img/servant/thumb/Molay.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Lady Avalon", "view/assets/img/servant/Avalon.png", "view/assets/img/servant/thumb/Avalon.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Koyanskaya of Light", "view/assets/img/servant/koyanskaya.png", "view/assets/img/servant/thumb/koyanskaya.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Charlotte Corday (Summer)", "view/assets/img/servant/Charlotte_Summer.png", "view/assets/img/servant/thumb/Charlotte_Summer.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Zhuge Liang", "view/assets/img/servant/Liang.png", "view/assets/img/servant/thumb/Liang.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Artoria (Caster)", "view/assets/img/servant/Castoria.png", "view/assets/img/servant/thumb/Castoria.png", false);
INSERT INTO servant (name, image_url, thumbnail_url, is_has) VALUES ("Captain Nemo", "view/assets/img/servant/Nemo.png", "view/assets/img/servant/thumb/Nemo.png", false);

-- Insert skills --
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (1,"Eye of the Mind (False) B",10,"view/assets/img/skill/Evade.png",1,1);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (2,"Projection Magecraft B",10,"view/assets/img/skill/Quick-Arts-Buster-Up.png",2,1);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (3,"Kiss Demon B",10,"view/assets/img/skill/NP-Gain.png",3,1);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (4,"Swan Lake A",10,"view/assets/img/skill/Arts-Up.png",1,2);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (5,"Perfect Fluid B",10,"view/assets/img/skill/Water-Field.png",2,2);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (6,"Melt Envy EX",10,"view/assets/img/skill/NP-Drain.png",3,2);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (7,"Monstrous Strength C-",10,"view/assets/img/skill/ATK-Up.png",1,3);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (8,"Trap of Argalia: Down with a Touch! D",10,"view/assets/img/skill/Stun.png",2,3);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (9,"Evaporation of Sanity D",10,"view/assets/img/skill/Star-Turn.png",3,3);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (10,"Cheerful-Type Mystic Code (Younger Sister) A",10,"view/assets/img/skill/Arts-Up.png",1,4);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (11,"Maiden"s Willpower B",8,"view/assets/img/skill/Guts.png",2,4);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (12,"Wish of the Child of God EX",10,"view/assets/img/skill/NP-Gain.png",3,4);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (13,"Four Gods Divination (Hakuro) A",10,"view/assets/img/skill/DEF-Up.png",1,5);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (14,"Chiyogami Manipulation EX",10,"view/assets/img/skill/NP-Gain.png",2,5);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (15,"Castle Ghost A++",10,"view/assets/img/skill/DEF-Down.png",3,5);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (16,"Self-Modification EX",10,"view/assets/img/skill/Crit-Up.png",1,6);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (17,"Aurea Porc Pocua: Golden Pig Grail A",10,"view/assets/img/skill/NP-Gain.png",2,6);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (18,"Faceless Moon EX",10,"view/assets/img/skill/Card-Lock.png",3,6);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (19,"Cheerful-Type Mystic Code A",10,"view/assets/img/skill/Buster-Up.png",1,7);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (20,"Child of Nature B",10,"view/assets/img/skill/Invincible.png",2,7);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (21,"Suspicious Medicine A",10,"view/assets/img/skill/Heal.png",3,7);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (22,"High-Speed Sutra Chanting A",10,"view/assets/img/skill/NP-Gain.png",1,8);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (23,"Bewitching Rosy Cheeks A",10,"view/assets/img/skill/Taunt.png",2,8);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (24,"Sanzang"s Teachings A",10,"view/assets/img/skill/NP-Gain-Up.png",3,8);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (25,"Physical Strength of Natural Surroundings A+",10,"view/assets/img/skill/ATK-Up.png",1,9);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (26,"Eight Channels Surging Waves B",10,"view/assets/img/skill/Buster-Up.png",2,9);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (27,"Defiled Fingertips A",10,"view/assets/img/skill/Debuff.png",3,9);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (28,"Casseur de Logistille C",10,"view/assets/img/skill/NP-Turn.png",1,10);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (29,"La Black Luna C",10,"view/assets/img/skill/Stun.png",2,10);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (30,"Majestic Triumphal Return EX",10,"view/assets/img/skill/ATK-Up.png",3,10);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (31,"Mana Burst A",10,"view/assets/img/skill/Buster-Up.png",1,11);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (32,"Cigarette Lion B+",10,"view/assets/img/skill/Buster-Star-Absorb.png",2,11);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (33,"Secret of Pedigree: Helm of Hidden Infidelity EX",10,"view/assets/img/skill/DEF-Up.png",3,11);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (34,"Military Tactics B",10,"view/assets/img/skill/NP-Up.png",1,12);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (35,"Natural Body D",10,"view/assets/img/skill/Debuff-Res.png",2,12);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (36,"Star Emblem EX",10,"view/assets/img/skill/ATK-Up.png",3,12);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (37,"Stout Arm of Brutality B+",10,"view/assets/img/skill/Buster-Up.png",1,13);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (38,"Pressure of the Moon Goddess EX",10,"view/assets/img/skill/Guts.png",2,13);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (39,"Bowman of Three Stars A+",10,"view/assets/img/skill/Star-Absorb-Up.png",3,13);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (40,"Merit of Clermont B",10,"view/assets/img/skill/Quick-Arts-Up.png",1,14);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (41,"Paladin of the White Feather B+",10,"view/assets/img/skill/Guts.png",2,14);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (42,"Thaumaturgy Sanctification A",10,"view/assets/img/skill/NP-Gain.png",3,14);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (43,"Beach Flower EX",10,"view/assets/img/skill/ATK-Up.png",1,15);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (44,"Midsummer Witchcraft A",10,"view/assets/img/skill/Charm.png",2,15);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (45,"Goddess Metamorphosis B",10,"view/assets/img/skill/Invincible.png",3,15);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (46,"Drómos Komḗtēs A+",10,"view/assets/img/skill/Quick-Up.png",1,16);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (47,"Andreíos Amárantos B",10,"view/assets/img/skill/Invincible.png",2,16);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (48,"Diatrekhōn Astēr Lonkhē B+",10,"view/assets/img/skill/Taunt.png",3,16);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (49,"Rampaging Privilege EX",10,"view/assets/img/skill/NP-Gain.png",1,17);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (50,"Seven Crowns C",10,"view/assets/img/skill/ATK-DEF-Up.png",2,17);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (51,"Undying Magus A",10,"view/assets/img/skill/Guts.png",3,17);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (52,"Fire Support EX",10,"view/assets/img/skill/Stun.png",1,18);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (53,"Instinct C+",10,"view/assets/img/skill/Star-Gain.png",2,18);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (54,"Galaxy Meteor Sword C",10,"view/assets/img/skill/Star-Drop-Up.png",3,18);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (55,"Murderer of the Misty Night A",10,"view/assets/img/skill/Evade.png",1,19);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (56,"Information Erasure B",10,"view/assets/img/skill/Debuff.png",2,19);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (57,"Surgery E",10,"view/assets/img/skill/Heal.png",3,19);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (58,"Self-Modification EX",10,"view/assets/img/skill/Crit-Up.png",1,20);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (59,"Dragon Witch EX",10,"view/assets/img/skill/ATK-Up.png",2,20);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (60,"Ephemeral Dream A",10,"view/assets/img/skill/Buster-Up.png",3,20);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (61,"Prosperous Business A",10,"view/assets/img/skill/NP-Gain.png",1,21);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (62,"Severed Tusk B",10,"view/assets/img/skill/Taunt.png",2,21);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (63,"Vinayaka EX",10,"view/assets/img/skill/Invincible.png",3,21);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (64,"Void Space Fine Arts B+",10,"view/assets/img/skill/Guts.png",1,22);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (65,"Het Gele Huis A+",10,"view/assets/img/skill/DEF-Down.png",2,22);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (66,"Soul of Water Channels EX",10,"view/assets/img/skill/ATK-Up.png",3,22);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (67,"Prayer of Creed C",10,"view/assets/img/skill/NP-Turn.png",1,23);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (68,"Mass Hysteria B",10,"view/assets/img/skill/Stun.png",2,23);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (69,"Witch Trial A+",10,"view/assets/img/skill/NP-Drain.png",3,23);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (70,"Happy Comrades A",10,"view/assets/img/skill/Buster-Up.png",1,24);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (71,"Lake of Bean Soup A",10,"view/assets/img/skill/Heal.png",2,24);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (72,"Popcorn Blizzard B",10,"view/assets/img/skill/DEF-Down.png",3,24);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (73,"Footed-Santa A",10,"view/assets/img/skill/Quick-Buster-Up.png",1,25);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (74,"Flashing Fist A",10,"view/assets/img/skill/Evade.png",2,25);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (75,"Hero of Charity (Holy Night) EX",10,"view/assets/img/skill/NP-Gain.png",3,25);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (76,"Midnight of Summerside A",10,"view/assets/img/skill/Guts.png",1,26);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (77,"VR Shinkage-ryū B+",10,"view/assets/img/skill/Arts-Up.png",2,26);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (78,"Survival (Countryside) B+",10,"view/assets/img/skill/Star-Gain.png",3,26);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (79,"Supernatural Power (Ink) C",10,"view/assets/img/skill/NP-Gain.png",1,27);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (80,"Father-Daughter Affinity B",10,"view/assets/img/skill/Star-Absorb-Up.png",2,27);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (81,"Nom de Plume: Dragon-Crested Octopus B",10,"view/assets/img/skill/Arts-Up.png",3,27);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (82,"Beauty-Concealing Mask A",10,"view/assets/img/skill/Invincible.png",1,28);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (83,"Vigorous Like the Breaking Bamboo C",10,"view/assets/img/skill/NP-Gain.png",2,28);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (84,"Demonic Face EX",10,"view/assets/img/skill/Arts-Up.png",3,28);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (85,"Golden Rule (Body) A",10,"view/assets/img/skill/Heal-Turn.png",1,29);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (86,"Charisma B",10,"view/assets/img/skill/ATK-Up.png",2,29);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (87,"Siren Song C",10,"view/assets/img/skill/Charm.png",3,29);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (88,"Supernatural Power B",10,"view/assets/img/skill/Buster-Up.png",1,30);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (89,"Mystic Eyes B+",10,"view/assets/img/skill/Charm.png",2,30);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (90,"Blessing of Wisdom C",10,"view/assets/img/skill/NP-Turn.png",3,30);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (91,"Avaricious Gold A",10,"view/assets/img/skill/NP-Gain-Up.png",1,31);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (92,"Disengage A",10,"view/assets/img/skill/Cure.png",2,31);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (93,"Dragon Slayer A++",10,"view/assets/img/skill/Special-Damage.png",3,31);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (94,"Goblet of Wealth B",10,"view/assets/img/skill/NP-Gain.png",1,32);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (95,"Imperial Privilege EX",10,"view/assets/img/skill/Heal.png",2,32);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (96,"Invictus Spiritus A",10,"view/assets/img/skill/Guts.png",3,32);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (97,"Instinct B",10,"view/assets/img/skill/Star-Gain.png",1,33);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (98,"Mana Burst A",10,"view/assets/img/skill/Buster-Up.png",2,33);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (99,"Journey of Flowers EX",10,"view/assets/img/skill/NP-Gain-Up.png",3,33);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (100,"Mana Burst A",10,"view/assets/img/skill/Buster-Up.png",1,34);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (101,"Instinct B",10,"view/assets/img/skill/Star-Gain.png",2,34);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (102,"Charisma E",10,"view/assets/img/skill/ATK-Up.png",3,34);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (103,"Assault Medicine C+",10,"view/assets/img/skill/Debuff.png",1,35);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (104,"Nurse of Steel (Holy Night) A",10,"view/assets/img/skill/Guts.png",2,35);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (105,"The Angel that Rings the Bell on Holy Night EX",10,"view/assets/img/skill/ATK-Up.png",3,35);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (106,"Sabotage B",10,"view/assets/img/skill/ATK-Down.png",1,36);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (107,"Galaxy Messenger EX",10,"view/assets/img/skill/NP-Drain.png",2,36);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (108,"O" Polar Star, Shine My Way B",10,"view/assets/img/skill/Debuff-Res.png",3,36);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (109,"Starman"s Gift B",10,"view/assets/img/skill/NP-Gain.png",1,37);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (110,"Rainbow Candy Crafts B",10,"view/assets/img/skill/NP-Up.png",2,37);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (111,"Twinkling Star Emblem EX",10,"view/assets/img/skill/Piercing.png",3,37);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (112,"Demonic Nature of Oni B",10,"view/assets/img/skill/ATK-Up.png",1,38);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (113,"Knowledge of Chaotic Battle B",10,"view/assets/img/skill/Star-Absorb-Up.png",2,38);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (114,"Adrenaline Rush A",10,"view/assets/img/skill/Guts.png",3,38);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (115,"Summer Incarnated Spirit A+",10,"view/assets/img/skill/Guts.png",1,39);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (116,"Tyrant"s Concubine EX",10,"view/assets/img/skill/NP-Gain.png",2,39);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (117,"Dance of Days Past EX",10,"view/assets/img/skill/Quick-Up.png",3,39);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (118,"Dread Spirit Peacekeeper A",10,"view/assets/img/skill/Arts-Up.png",1,40);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (119,"Der Freischütz (Imitation) B",10,"view/assets/img/skill/Sure-Hit.png",2,40);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (120,"Grim Reaper B",10,"view/assets/img/skill/Death-Up.png",3,40);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (121,"Fate is in Heaven A",10,"view/assets/img/skill/Arts-Up.png",1,41);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (122,"Armor is on the Chest A",10,"view/assets/img/skill/Evade.png",2,41);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (123,"Accomplishment is in the Feet A",10,"view/assets/img/skill/ATK-Up.png",3,41);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (124,"Primeval Rune",10,"view/assets/img/skill/Quick-Up.png",1,42);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (125,"Swan Mystic Code A",10,"view/assets/img/skill/Evade.png",2,42);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (126,"Fateweaver B",10,"view/assets/img/skill/NP-Turn.png",3,42);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (127,"Siren Song B",10,"view/assets/img/skill/Charm.png",1,43);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (128,"Monstrous Strength C-",10,"view/assets/img/skill/ATK-Up.png",2,43);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (129,"Affection Towards The Beyond A",10,"view/assets/img/skill/Guts.png",3,43);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (130,"Saint"s Gift C",10,"view/assets/img/skill/Heal.png",1,44);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (131,"Self-Upheaval A",10,"view/assets/img/skill/NP-Gain.png",2,44);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (132,"Ephemeral Dream EX",10,"view/assets/img/skill/Buster-Up.png",3,44);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (133,"Battle Continuation C",10,"view/assets/img/skill/Guts.png",1,45);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (134,"Gareth Beaumains B",10,"view/assets/img/skill/NP-Gain.png",2,45);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (135,"Ring of Transformation B",10,"view/assets/img/skill/Taunt.png",3,45);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (136,"Voyage A",10,"view/assets/img/skill/Star-Drop-Up.png",1,46);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (137,"Marksmanship B",10,"view/assets/img/skill/Crit-Up.png",2,46);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (138,"Combination C",10,"view/assets/img/skill/Star-Absorb-Up.png",3,46);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (139,"Siren Song C",10,"view/assets/img/skill/Charm.png",1,47);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (140,"Princess of Loveliness A",10,"view/assets/img/skill/Invincible.png",2,47);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (141,"Grace of God B",10,"view/assets/img/skill/Debuff-Up.png",3,47);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (142,"Witchcraft EX",10,"view/assets/img/skill/NP-Drain.png",1,48);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (143,"Shapeshift A",10,"view/assets/img/skill/DEF-Up.png",2,48);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (144,"Fox"s Wedding EX",10,"view/assets/img/skill/Arts-Up.png",3,48);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (145,"Heart Break: Oni of Dharmapala - Heart Ripper A+",10,"view/assets/img/skill/Debuff.png",1,49);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (146,"Break Rod: Oni of Dharmapala - Bludgeoning Club B",10,"view/assets/img/skill/Arts-Buster-Up.png",2,49);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (147,"Demonic Nature of Oni (Protection) A",10,"view/assets/img/skill/ATK-Up.png",3,49);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (148,"Man-made Hero (False) B+",10,"view/assets/img/skill/NP-Gain-Up.png",1,50);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (149,"Magecraft C",10,"view/assets/img/skill/Arts-Up.png",2,50);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (150,"Dead Count Shapeshifter EX",10,"view/assets/img/skill/Special-Damage.png",3,50);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (151,"Charisma B-",10,"view/assets/img/skill/ATK-Up.png",1,51);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (152,"Spiritual VIsion A",10,"view/assets/img/skill/Crit-Up.png",2,51);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (153,"Demon God"s Wisdom A",10,"view/assets/img/skill/Arts-Buster-Up.png",3,51);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (154,"King"s Return A",10,"view/assets/img/skill/Star-Drop-Up.png",1,52);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (155,"Charisma A+",10,"view/assets/img/skill/ATK-Up.png",2,52);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (156,"Sovereign of Magic Wands EX",10,"view/assets/img/skill/Arts-Up.png",3,52);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (157,"Sacrificial Resolve A",10,"view/assets/img/skill/Heal-Up.png",1,53);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (158,"Child of Nature A",10,"view/assets/img/skill/Invincible.png",2,53);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (159,"Healing Magecraft A",10,"view/assets/img/skill/Heal.png",3,53);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (160,"Eternally-Peerless Blade A+",10,"view/assets/img/skill/Quick-Up.png",1,54);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (161,"Onmyōdō (Law) A",10,"view/assets/img/skill/NP-Gain.png",2,54);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (162,"Six Secret Arts of War EX",10,"view/assets/img/skill/ATK-Up.png",3,54);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (163,"Jet Ten"nen Rishin-ryū A+",10,"view/assets/img/skill/Crit-Up.png",1,55);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (164,"Eye of the Mind (J) A-",10,"view/assets/img/skill/Evade.png",2,55);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (165,"M DRIVE EX",10,"view/assets/img/skill/Quick-Up.png",3,55);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (166,"Anti-Spirit Combat B",10,"view/assets/img/skill/ATK-Up.png",1,56);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (167,"Sealing Mystic Code Release C",10,"view/assets/img/skill/Quick-Buster-Up.png",2,56);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (168,"Protection of World"s End B",10,"view/assets/img/skill/NP-Gain.png",3,56);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (169,"Animal Dialogue D",10,"view/assets/img/skill/NP-Gain.png",1,57);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (170,"Tengu Art of Game (Summer) EX",10,"view/assets/img/skill/Evade.png",2,57);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (171,"Heavenly Child of Kurama A+",10,"view/assets/img/skill/Star-Absorb-Up.png",3,57);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (172,"Witchcraft (Shrine Maiden) C",10,"view/assets/img/skill/Debuff.png",1,58);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (173,"Curse of Orochi B",10,"view/assets/img/skill/Arts-Up.png",2,58);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (174,"Kōga-ryū A",10,"view/assets/img/skill/Evade.png",3,58);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (175,"White Imperial Garments A",10,"view/assets/img/skill/DEF-Up.png",1,59);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (176,"Beach Panic EX",10,"view/assets/img/skill/Taunt.png",2,59);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (177,"Royal Road of Hot Sands A",10,"view/assets/img/skill/ATK-Up.png",3,59);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (178,"Torture Technique A",10,"view/assets/img/skill/DEF-Down.png",1,60);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (179,"Imperial Privilege B",10,"view/assets/img/skill/Heal.png",2,60);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (180,"Charisma of the Empress A",10,"view/assets/img/skill/ATK-Up.png",3,60);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (181,"Bloodsucker C",10,"view/assets/img/skill/NP-Drain.png",1,61);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (182,"Siren Song A",10,"view/assets/img/skill/Charm.png",2,61);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (183,"Whim of Goddess A",10,"view/assets/img/skill/ATK-Up.png",3,61);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (184,"Genji-clan Martial Arts Discipline EX",10,"view/assets/img/skill/Star-Absorb-Up.png",1,62);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (185,"Mana Burst (Lightning) A",10,"view/assets/img/skill/Buster-Up.png",2,62);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (186,"Mystery Killer A",10,"view/assets/img/skill/Special-Damage.png",3,62);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (187,"Schwarzwald Falke B",10,"view/assets/img/skill/Evade.png",1,63);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (188,"Fallen Witch A+",10,"view/assets/img/skill/ATK-Up.png",2,63);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (189,"Meurs Où tu Dois EX",10,"view/assets/img/skill/Buster-Up.png",3,63);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (190,"Self Evolution EX",10,"view/assets/img/skill/Star-Absorb-Up.png",1,64);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (191,"Crossing Arcadia A",10,"view/assets/img/skill/Quick-Up.png",2,64);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (192,"Wild Beast"s Logic B",10,"view/assets/img/skill/Evade.png",3,64);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (193,"Foolish Murder Style A",10,"view/assets/img/skill/Evade.png",1,65);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (194,"Atsumori Beat B",10,"view/assets/img/skill/Star-Turn.png",2,65);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (195,"Sixth Heaven Demon King of the Beach A-",10,"view/assets/img/skill/Star-Absorb-Up.png",3,65);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (196,"Charisma B",10,"view/assets/img/skill/ATK-Up.png",1,66);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (197,"Golden Rule (Beauty) A",10,"view/assets/img/skill/Debuff-Immune.png",2,66);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (198,"Bellow of Ares A+",10,"view/assets/img/skill/Buster-Up.png",3,66);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (199,"Waterfront Saintess B+",10,"view/assets/img/skill/NP-Gain.png",1,67);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (200,"Natural Body (Ocean) A",10,"view/assets/img/skill/Debuff-Immune.png",2,67);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (201,"Jacob"s Limbs B",10,"view/assets/img/skill/Special-Damage.png",3,67);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (202,"Innocent Kaiju EX",10,"view/assets/img/skill/Star-Turn.png",1,68);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (203,"Overload (Revised) C",10,"view/assets/img/skill/NP-Gain.png",2,68);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (204,"Final Eli-chan C",10,"view/assets/img/skill/NP-Up.png",3,68);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (205,"Breast Valley A",10,"view/assets/img/skill/DEF-Up.png",1,69);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (206,"Masochistic Constitution A",10,"view/assets/img/skill/Taunt.png",2,69);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (207,"Trash and Crash EX",10,"view/assets/img/skill/ATK-DEF-Up.png",3,69);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (208,"Piloting EX",10,"view/assets/img/skill/Invincible.png",1,70);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (209,"Detective"s Instinct E",10,"view/assets/img/skill/Star-Gain.png",2,70);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (210,"Justice from the Ends of the World A",10,"view/assets/img/skill/Piercing.png",3,70);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (211,"Black Barrel B",10,"view/assets/img/skill/Buster-Up.png",1,71);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (212,"Amalgam Goad D",10,"view/assets/img/skill/Taunt.png",2,71);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (213,"Shield of Rousing Heroism",10,"view/assets/img/skill/Invincible.png",3,71);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (214,"Domina Coronam: Ten Crowns D",10,"view/assets/img/skill/Cure.png",1,72);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (215,"Aurea Pocula: Golden Grail C",10,"view/assets/img/skill/Stun.png",2,72);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (216,"Self-Modification EX",10,"view/assets/img/skill/Crit-Up.png",3,72);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (217,"Self-Modification A",10,"view/assets/img/skill/Crit-Up.png",1,73);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (218,"Shapeshift A+",10,"view/assets/img/skill/DEF-Up.png",2,73);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (219,"Meanwhile A",10,"view/assets/img/skill/NP-Gain.png",3,73);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (220,"Magical Tuning C",10,"view/assets/img/skill/NP-Gain.png",1,74);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (221,"Mahatma A",10,"view/assets/img/skill/Star-Turn.png",2,74);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (222,"Pursuit of the Unknown B",10,"view/assets/img/skill/Quick-Arts-Buster-Up.png",3,74);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (223,"Heroine"s Great Principle EX",10,"view/assets/img/skill/Invincible.png",1,75);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (224,"Mana Burst (Courage) D",10,"view/assets/img/skill/Buster-Up.png",2,75);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (225,"Legend of the Crimson Heroine EX",10,"view/assets/img/skill/Special-Damage.png",3,75);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (226,"Eye of the Mind (True) C",10,"view/assets/img/skill/Evade.png",1,76);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (227,"Self-Suggestion A",10,"view/assets/img/skill/Cure.png",2,76);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (228,"Looks of Loveliness C",10,"view/assets/img/skill/Taunt-Special.png",3,76);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (229,"Beach Flower A+",10,"view/assets/img/skill/ATK-Up.png",1,77);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (230,"Treasure Hunt (Ocean) A",10,"view/assets/img/skill/Star-Absorb-Up.png",2,77);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (231,"Pirate"s Honor C+",10,"view/assets/img/skill/ATK-Up.png",3,77);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (232,"Strategy B",10,"view/assets/img/skill/NP-Gain-Up.png",1,78);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (233,"Tenka Fubu A",10,"view/assets/img/skill/Special-Damage.png",2,78);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (234,"Demon King A",10,"view/assets/img/skill/Crit-Up.png",3,78);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (235,"Robust Health EX",10,"view/assets/img/skill/DEF-Up.png",1,79);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (236,"Clairvoyance A",10,"view/assets/img/skill/Star-Drop-Up.png",2,79);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (237,"Bow and Arrow Creation A",10,"view/assets/img/skill/NP-Gain.png",3,79);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (238,"Blazing Summer Passion A",10,"view/assets/img/skill/Crit-Rate-Down.png",1,80);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (239,"Bathing Transformation A",10,"view/assets/img/skill/Buster-Up.png",2,80);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (240,"Pursuer of Love A",10,"view/assets/img/skill/DEF-Down.png",3,80);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (241,"Charisma C",10,"view/assets/img/skill/ATK-Up.png",1,81);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (242,"Torture Technique A",10,"view/assets/img/skill/DEF-Down.png",2,81);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (243,"Battle Continuation B",10,"view/assets/img/skill/Guts.png",3,81);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (244,"Glittering Aquatic Gown A",10,"view/assets/img/skill/Quick-Buster-Up.png",1,82);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (245,"Accel Turn B",10,"view/assets/img/skill/Evade.png",2,82);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (246,"Summer Breaker! A",10,"view/assets/img/skill/Invincible.png",3,82);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (247,"Armour of Nine Worthies A",10,"view/assets/img/skill/ATK-DEF-Up.png",1,83);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (248,"Errant Blow C",10,"view/assets/img/skill/ATK-Up.png",2,83);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (249,"Brigliadoro"s Neigh A",10,"view/assets/img/skill/Quick-Arts-Up.png",3,83);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (250,"Egypt Magecraft A",10,"view/assets/img/skill/Death-Up.png",1,84);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (251,"High-Speed Divine Words B",10,"view/assets/img/skill/NP-Gain.png",2,84);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (252,"Affection of Horus B",10,"view/assets/img/skill/Guts.png",3,84);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (253,"Human Observation A",10,"view/assets/img/skill/Crit-Up.png",1,85);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (254,"High-Speed Incantation E",10,"view/assets/img/skill/NP-Gain.png",2,85);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (255,"Innocent Monster D",10,"view/assets/img/skill/Star-Turn.png",3,85);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (256,"Beach Crisis A+",10,"view/assets/img/skill/Taunt.png",1,86);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (257,"Primeval Rune (Ocean) A",10,"view/assets/img/skill/Heal.png",2,86);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (258,"Midsummer Faux Pas C",10,"view/assets/img/skill/Piercing.png",3,86);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (259,"Golden Rule (Calamity) B",10,"view/assets/img/skill/NP-Turn.png",1,87);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (260,"Innocent Monster (Flame) C",10,"view/assets/img/skill/Star-Turn.png",2,87);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (261,"Favored Princess of Japan EX",10,"view/assets/img/skill/DEF-Down.png",3,87);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (262,"Demonic Nature of Oni A",10,"view/assets/img/skill/ATK-Up.png",1,88);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (263,"Disengage A",10,"view/assets/img/skill/Cure.png",2,88);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (264,"Shapeshift A",10,"view/assets/img/skill/DEF-Up.png",3,88);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (265,"Galvanism B",10,"view/assets/img/skill/NP-Gain-Up.png",1,89);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (266,"Lament of the Falsely Living C",10,"view/assets/img/skill/Stun.png",2,89);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (267,"Overload C",10,"view/assets/img/skill/NP-Up.png",3,89);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (268,"Monstrous Strength B",10,"view/assets/img/skill/ATK-Up.png",1,90);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (269,"Witchcraft EX",10,"view/assets/img/skill/NP-Drain.png",2,90);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (270,"Shapeshift B",10,"view/assets/img/skill/DEF-Up.png",3,90);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (271,"Monstrous Strength A+",10,"view/assets/img/skill/ATK-Up.png",1,91);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (272,"Demonic Mutation B",10,"view/assets/img/skill/Guts.png",2,91);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (273,"Mystic Eyes A++",10,"view/assets/img/skill/Stun.png",3,91);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (274,"Innocent Monster EX",10,"view/assets/img/skill/Star-Turn.png",1,92);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (275,"Wailing Facade A",10,"view/assets/img/skill/Arts-Up.png",2,92);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (276,"Wildfire B",10,"view/assets/img/skill/DEF-Down.png",3,92);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (277,"Eyes of Apollo (False) B+",10,"view/assets/img/skill/Evade.png",1,93);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (278,"Affection of Male God B",10,"view/assets/img/skill/ATK-DEF-Up.png",2,93);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (279,"Dystychía Milo: Golden Apple of Discord EX",10,"view/assets/img/skill/NP-Gain.png",3,93);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (280,"Blood-Soaked Silver Plate B+",10,"view/assets/img/skill/Special-Damage.png",1,94);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (281,"Natural Body (Body) C",10,"view/assets/img/skill/Debuff-Immune.png",2,94);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (282,"Dance of the Seven Veils A",10,"view/assets/img/skill/Heal-Turn.png",3,94);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (283,"Charisma A+",10,"view/assets/img/skill/ATK-Up.png",1,95);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (284,"Rosy-cheeked Adonis C",10,"view/assets/img/skill/Charm.png",2,95);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (285,"Golden Rule A",10,"view/assets/img/skill/NP-Gain-Up.png",3,95);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (286,"Bloodsucker C",10,"view/assets/img/skill/NP-Drain.png",1,96);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (287,"Siren Song A",10,"view/assets/img/skill/Charm.png",2,96);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (288,"Whim of Goddess A",10,"view/assets/img/skill/Arts-Up.png",3,96);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (289,"Artless Stratagem D",10,"view/assets/img/skill/Debuff.png",1,97);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (290,"Into the Heavens I Sacrifice B",10,"view/assets/img/skill/Star-Turn.png",2,97);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (291,"War-torn Flower C",10,"view/assets/img/skill/Taunt.png",3,97);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (292,"Tengu Art of War A",10,"view/assets/img/skill/NP-Gain-Up.png",1,98);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (293,"Charisma C+",10,"view/assets/img/skill/ATK-Up.png",2,98);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (294,"Art of the Swallow B",10,"view/assets/img/skill/Evade.png",3,98);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (295,"Oath to the Goddess B",10,"view/assets/img/skill/Special-Damage.png",1,99);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (296,"Battle Continuation A",10,"view/assets/img/skill/Guts.png",2,99);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (297,"Protection from Andraste A",10,"view/assets/img/skill/Arts-Up.png",3,99);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (298,"Mystic Eyes A+",10,"view/assets/img/skill/Stun.png",1,100);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (299,"Monstrous Strength B",10,"view/assets/img/skill/ATK-Up.png",2,100);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (300,"Blood Fort Andromeda: Blood Temple B",10,"view/assets/img/skill/NP-Gain.png",3,100);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (301,"Shapeshift (Inflitration Specialization) C",10,"view/assets/img/skill/Crit-Rate-Down.png",1,101);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (302,"Poisonous Dagger C++",10,"view/assets/img/skill/Poison.png",2,101);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (303,"Silent Dance B",10,"view/assets/img/skill/Death-Up.png",3,101);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (304,"Angel of Assassination A",10,"view/assets/img/skill/Death-Up.png",1,102);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (305,"Determination of Steel D",10,"view/assets/img/skill/Piercing.png",2,102);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (306,"Ludicrous Planning D+",10,"view/assets/img/skill/Special-Damage.png",3,102);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (307,"Espionage A++",10,"view/assets/img/skill/Star-Drop-Up.png",1,103);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (308,"Pheromone B",10,"view/assets/img/skill/Charm.png",2,103);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (309,"Double Cross B",10,"view/assets/img/skill/Debuff.png",3,103);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (310,"Shapeshift C",10,"view/assets/img/skill/DEF-Up.png",1,104);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (311,"Stalking B",10,"view/assets/img/skill/DEF-Down.png",2,104);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (312,"Flame-Coloured Kiss A",10,"view/assets/img/skill/Buster-Up.png",3,104);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (313,"Sealing Designation Enforcer A",10,"view/assets/img/skill/Quick-Buster-Up.png",1,105);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (314,"Sea God\'s Rune EX",10,"view/assets/img/skill/NP-Gain.png",2,105);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (315,"Succession of the Red Branch B",10,"view/assets/img/skill/Evade.png",3,105);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (316,"Charisma of the Rebellion B-",10,"view/assets/img/skill/ATK-Up.png",1,106);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (317,"Sisters Bond A",10,"view/assets/img/skill/Arts-Buster-Up.png",2,106);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (318,"Exalted Queen Trung EX",10,"view/assets/img/skill/NP-Gain.png",3,106);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (319,"Charisma of the Jade A+",10,"view/assets/img/skill/ATK-Up.png",1,107);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (320,"We are the Winged Serpent EX",10,"view/assets/img/skill/NP-Gain.png",2,107);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (321,"Golden Sea of Trees Travelogue EX",10,"view/assets/img/skill/Invincible.png",3,107);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (322,"Veiling of Depravity A",10,"view/assets/img/skill/ATK-Up.png",1,108);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (323,"Shroud of Turin (Fake) B",10,"view/assets/img/skill/Invincible.png",2,108);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (324,"Innocent Monster A",10,"view/assets/img/skill/Star-Turn.png",3,108);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (325,"Light Upon That Hand B",10,"view/assets/img/skill/Arts-Up.png",1,109);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (326,"Blooming Flower of Summer Nights D",10,"view/assets/img/skill/ATK-Up.png",2,109);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (327,"Succubus\' Ridge EX",10,"view/assets/img/skill/Invincible.png",3,109);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (328,"Innovator Bunny A",10,"view/assets/img/skill/NP-Gain.png",1,110);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (329,"Aptitude for Slaughter (Man) A",10,"view/assets/img/skill/Special-Damage.png",2,110);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (330,"NFF Special A",10,"view/assets/img/skill/Buster-Up.png",3,110);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (331,"Illusionist (False) C+",10,"view/assets/img/skill/Arts-Up.png",1,111);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (332,"Ludicrous Show Planning A",10,"view/assets/img/skill/Debuff.png",2,111);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (333,"Angel of Tricks EX",10,"view/assets/img/skill/NP-Gain.png",3,111);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (334,"Discerning Eye A",10,"view/assets/img/skill/Crit-Up.png",1,112);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (335,"Advice of the Strategist A+",10,"view/assets/img/skill/DEF-Up.png",2,112);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (336,"Command of the Strategist A+",10,"view/assets/img/skill/ATK-Up.png",3,112);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (337,"Charisma of Hope B",10,"view/assets/img/skill/ATK-Up.png",1,113);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (338,"Avalon le Fae A",10,"view/assets/img/skill/NP-Gain.png",2,113);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (339,"Caliburn: Sword of Selection EX",10,"view/assets/img/skill/Arts-Up.png",3,113);
INSERT INTO skill ("id", `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (340,"Voyager of the Storm C++",10,"view/assets/img/skill/NP-Up.png",1,114);
INSERT INTO skill ("id', `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (341,'Indomitable B+',10,'view/assets/img/skill/Guts.png',2,114);
INSERT INTO skill ('id', `name`, `level`, `image_url`, `seq`, `servant_id`) VALUES (342,'Journey\'s Guidance C++',10,'view/assets/img/skill/Arts-Up.png',3,114);